#!/usr/bin/env bash
# configure an Nginx server to listen on port 80

# creates a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory
ln -f /etc/nginx/sites-availables/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminates the first nginx process
kill "$(pgrep 'nginx' | head -1)"
